openapi: "3.0.0"
info: 
  title: hospital-management
  description: book-your-appointment
  version: 1.0.0
servers:
  - url: /
paths:
  /auth:
    get:
      description: To-verify-User-Login
      parameters:
        - name: email
          in: header
          required: true
          schema:
            type: string
        - name: password
          in: header
          required: true
          schema:
            type: string
      responses:
        200: 
          description: Login success