openapi: "3.0.0"
info:
  title: hospital-management
  description: book-your-appointment
  version: 1.0.0
servers:
  - url: /
tags:
  - name: Employee
  - name: Doctor
  - name: Slots
paths:
  /employee/auth:
    get:
      tags:
        - Employee
      description: To-verify-Employe-Login
      parameters:
        - name: email
          in: header
          required: true
          schema:
            type: string
        - name: password
          in: header
          required: true
          schema:
            type: string
      responses:
        200:
          description: Login success
  /employee:
    post:
      tags:
        - Employee
      description: To add an Employee
      operationId: addEmployee
      security:
        - BearerAuth: []
      requestBody:
        description: To add employee details
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/addEmployee"
      responses:
        200:
          description: Employee added sucessfully
    put:
      tags:
        - Employee
      description: to update an employee
      operationId: updateEmployee
      security:
        - BearerAuth: []
      requestBody:
        description: to update an employee
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/updateEmployee"
      responses:
        200:
          description: Employee updated sucessfully
  /doctors/auth:
    get:
      tags:
        - Doctor
      description: To-verify-Doctor-Login
      operationId: doctorAuth
      parameters:
        - name: email
          in: header
          required: true
          schema:
            type: string
        - name: password
          in: header
          required: true
          schema:
            type: string
      responses:
        200:
          description: Login success
  /doctors/all:
    get:
      tags:
        - Doctor
      description: To get all doctors
      operationId: getDoctors
      responses:
        200:
          description: request successfull
  /doctors:
    post:
      tags:
        - Doctor
      description: To add an Doctor
      operationId: postDoctor
      security:
        - BearerAuth: []
      requestBody:
        description: To add Doctor details
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/addDoctor"
      responses:
        200:
          description: Employee added sucessfully
    put:
      tags:
        - Doctor
      description: to update an Doctor
      security:
        - BearerAuth: []
      requestBody:
        description: to update an Doctor
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/updateEmployee"
      responses:
        200:
          description: Employee updated sucessfully
  /slots:
    get:
      tags:
        - Slots
      description: To get avilable slots by doctorid
      operationId: getAvilableSlotsByDoctorId
      parameters:
        - name: doctor_id
          in: header
          required: true
          schema:
            type: integer
      responses:
        200:
          description: request successfull
    post:
      tags:
        - Slots
      description: To add slots
      operationId: addSlot
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/addSlot"
      responses:
        200:
          description: Slot added sucessfully
    put:
      tags:
        - Slots
      description: To update slots
      operationId: updateSlot
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/updateSlot"
      responses:
        200:
          description: Slot updated sucessfully
  /slots/doctor:
    get:
      tags:
        - Slots
      description: To get all doctor slots
      operationId: getAllDoctorSlots
      security:
        - BearerAuth: []
      parameters:
        - name: doctor_id
          in: header
          required: true
          schema:
            type: integer
      responses:
        200:
          description: request successfull
  /appointments/current-queue:
    get:
      tags:
        - Appointments
      description: To get appointments current queue
      operationId: getAppointmentQueue
      parameters:
        - name: doctor_id
          in: header
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Appointment booked sucessfully
  /appointments/guest:
    post:
      tags:
        - Appointments
      description: To add appointments
      operationId: addGuestAppointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postGuestAppoitment"
      responses:
        200:
          description: Appointment booked sucessfully
  /appointments:
    get:
      tags:
        - Appointments
      description: Get appointements by slot_date
      security:
        - BearerAuth: []
      parameters:
        - name: created_date
          in: header
          required: true
          schema:
            type: string
      responses:
        200:
          description: appointements

    post:
      tags:
        - Appointments
      description: To add appointments
      operationId: addAppointment
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postAppoitment"
      responses:
        200:
          description: Appointment booked sucessfully
  /appointments/id:
    get:
      tags:
        - Appointments
      description: Get appointements by id
      operationId: getAppointmentById
      security:
        - BearerAuth: []
      parameters:
        - name: appointment_id
          in: header
          required: true
          schema:
            type: string
      responses:
        200:
          description: appointements
  /appointments/complete:
    patch:
      tags:
        - Appointments
      description: update the complete status by id
      operationId: updateCompleteAppointmentById
      security:
        - BearerAuth: []
      parameters:
        - name: appointment_id
          in: header
          required: true
          schema:
            type: string
      responses:
        200:
          description: appointements
  /appointments/cancel:
    patch:
      tags:
        - Appointments
      description: update the cancel status by id
      operationId: updateCancelAppointmentById
      security:
        - BearerAuth: []
      parameters:
        - name: appointment_id
          in: header
          required: true
          schema:
            type: string
      responses:
        200:
          description: appointements
components:
  schemas:
    addEmployee:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        mobile_number:
          type: integer
        gender:
          type: string
        password:
          type: string
        dob:
          type: string
        role:
          type: string
    updateEmployee:
      type: object
      properties:
        employee_id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        mobile_number:
          type: integer
        gender:
          type: string
        dob:
          type: string
        role:
          type: string
    addDoctor:
      type: object
      properties:
        image:
          type: string
          format: binary
        name:
          type: string
        email:
          type: string
        mobile_number:
          type: integer
        password:
          type: string
        dob:
          type: string
        specialization:
          type: string
        description: 
          type: string
    addSlot:
      type: object
      properties:
        description:
          type: string
        title:
          type: string
        doctor_id:
          type: integer
        available_slots:
          type: integer
        slot_date:
          type: string
        slot_time:
          type: string
        slot_end_time:
          type: string
    updateSlot:
      type: object
      properties:
        description:
          type: string
        title:
          type: string
        slot_id:
          type: integer
        available_slots:
          type: integer
        slot_date:
          type: string
        slot_time:
          type: string
        slot_end_time:
          type: string
    postGuestAppoitment:
      type: object
      properties:
        name:
          type: string
        mobile_number:
          type: integer
        email:
          type: string
        slot_id:
          type: integer
    postAppoitment:
      type: object
      properties:
        user_id:
          type: integer
        name:
          type: string
        mobile_number:
          type: integer
        email:
          type: string
        slot_id:
          type: integer
        is_emergency:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
